const C=document.querySelector("#game"),ctx=C.getContext("2d");let W,H,dpr;function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener("resize",resize);resize();
const login=document.querySelector("#login");document.querySelector("#google").onclick=()=>start("Google");document.querySelector("#discord").onclick=()=>start("Discord");function start(provider){login.classList.add("hidden");localStorage.setItem("hg_provider",provider);loop()}
const saved=JSON.parse(localStorage.getItem("hg_save")||"null");const player={x:0,y:0,hp:100,maxHp:100,mana:100,maxMana:100,aura:100,gold:saved?.gold||50,level:saved?.level||1,wood:saved?.wood||0,ore:saved?.ore||0,arrows:20};const keys=new Set();let mouse={x:0,y:0,down:false},entities=[],particles=[],time=0,seed=saved?.seed??Math.floor(Math.random()*1e9);const tile=48;
function rng(n){let x=Math.sin(n*12.9898+seed)*43758.5453;return x-Math.floor(x)}function noise(x,y){return rng(Math.floor(x/3)*928371+Math.floor(y/3)*1237)}function terrain(x,y){let n=noise(x,y),n2=noise(x+71,y-33);if(n<.035)return"water";if(n<.075)return"mountain";if(n>.95)return"sand";if(n2>.92)return"dead";return"grass"}function makeEntity(x,y,type){entities.push({x,y,type,hp:type==="mob"?35:1,hit:0,alive:true})}
function generate(){entities=[];for(let gx=-100;gx<=100;gx++)for(let gy=-100;gy<=100;gy++){let t=terrain(gx*tile,gy*tile),r=rng(gx*177+gy*331);if(t==="water")continue;if(r<.025)makeEntity(gx*tile+24,gy*tile+24,"tree");else if(t==="mountain"&&r<.12)makeEntity(gx*tile+24,gy*tile+24,"ore");else if(r<.008)makeEntity(gx*tile+24,gy*tile+24,"chest");else if(r<.012)makeEntity(gx*tile+24,gy*tile+24,"city");else if(r<.018)makeEntity(gx*tile+24,gy*tile+24,"mob")}for(let i=0;i<22;i++){let a=i*2.399;makeEntity(Math.cos(a)*1200,Math.sin(a)*1200,"cave")}}generate();
function save(){localStorage.setItem("hg_save",JSON.stringify({seed,gold:player.gold,level:player.level,wood:player.wood,ore:player.ore}))}function near(type,range=70){let b=null,bd=range;for(const e of entities)if(e.alive&&e.type===type){let d=Math.hypot(e.x-player.x,e.y-player.y);if(d<bd){bd=d;b=e}}return b}
function burst(x,y,c){for(let i=0;i<10;i++)particles.push({x,y,vx:(Math.random()-.5)*120,vy:(Math.random()-.5)*120,life:.45,c})}
function attack(){let a=Math.atan2(mouse.y-H/2,mouse.x-W/2);for(const e of entities){if(!e.alive||e.type!=="mob")continue;let dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy),ea=Math.atan2(dy,dx);if(d<95&&Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)))<.75){e.hp-=28;burst(e.x,e.y,"#fff");if(e.hp<=0){e.alive=false;player.gold+=8;if(Math.random()<.08)player.level++;}}}}
function spell(){if(player.mana<20)return;player.mana-=20;let a=Math.atan2(mouse.y-H/2,mouse.x-W/2);for(const e of entities)if(e.alive&&e.type==="mob"&&Math.hypot(e.x-player.x,e.y-player.y)<230){let ea=Math.atan2(e.y-player.y,e.x-player.x);if(Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)))<.9){e.hp-=50;if(e.hp<=0){e.alive=false;player.gold+=15}}}for(let i=0;i<24;i++)particles.push({x:player.x,y:player.y,vx:Math.cos(a)+(Math.random()-.5),vy:Math.sin(a)+(Math.random()-.5),life:.5,c:"#9c6cff"})}
function interact(){for(const type of["tree","ore","chest","city","cave"]){let e=near(type);if(!e)continue;if(type==="tree"){player.wood+=2;e.alive=false}if(type==="ore"){player.ore+=2;e.alive=false}if(type==="chest"){player.gold+=25;e.alive=false}if(type==="city"){player.gold+=5;player.hp=player.maxHp;player.mana=player.maxMana}if(type==="cave"){player.ore+=5;e.alive=false}save();break}}
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key===" ")e.preventDefault();if(e.key.toLowerCase()==="q")spell();if(e.key.toLowerCase()==="f")interact();if(e.key.toLowerCase()==="e")attack()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));C.onmousemove=e=>{mouse.x=e.clientX;mouse.y=e.clientY};C.onmousedown=()=>mouse.down=true;C.onmouseup=()=>mouse.down=false;C.ontouchstart=e=>{let t=e.touches[0];mouse.x=t.clientX;mouse.y=t.clientY;mouse.down=true};C.ontouchend=()=>mouse.down=false;document.querySelectorAll("#mobile button").forEach(b=>b.ontouchstart=e=>{e.preventDefault();let k=b.dataset.k;if(k===" ")keys.add(" ");else if(k==="q")spell();else attack()});
function update(dt){let vx=(keys.has("d")?1:0)-(keys.has("a")?1:0),vy=(keys.has("s")?1:0)-(keys.has("w")?1:0),l=Math.hypot(vx,vy)||1;player.x+=vx/l*170*dt;player.y+=vy/l*170*dt;let blocking=keys.has(" ");player.mana=Math.min(100,player.mana+10*dt);player.aura=Math.max(0,Math.min(100,player.aura+(blocking?-18:10)*dt));if(mouse.down&&!blocking)attack();for(const e of entities){if(!e.alive||e.type!=="mob")continue;let d=Math.hypot(player.x-e.x,player.y-e.y);if(d<500){e.x+=(player.x-e.x)/d*20*dt;e.y+=(player.y-e.y)/d*20*dt;if(d<38&&e.hit<=0){if(blocking&&player.aura>10){player.aura-=10;burst(e.x,e.y,"#fff")}else player.hp-=12;e.hit=.8}}e.hit=Math.max(0,e.hit-dt)}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(player.hp<=0){player.hp=100;player.x=0;player.y=0;player.gold=Math.max(0,player.gold-20);save()}}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle="#17251b";ctx.fillRect(0,0,W,H);let ox=W/2-player.x,oy=H/2-player.y;let minx=Math.floor((player.x-W/2)/tile)-1,maxx=Math.floor((player.x+W/2)/tile)+1,miny=Math.floor((player.y-H/2)/tile)-1,maxy=Math.floor((player.y+H/2)/tile)+1;for(let gx=minx;gx<=maxx;gx++)for(let gy=miny;gy<=maxy;gy++){let t=terrain(gx*tile,gy*tile);ctx.fillStyle=t==="water"?"#244d70":t==="mountain"?"#4c4d48":t==="sand"?"#927c48":t==="dead"?"#3d3340":"#2d4b2c";ctx.fillRect(gx*tile+ox,gy*tile+oy,tile+1,tile+1)}for(const e of entities)if(e.alive){let x=e.x+ox,y=e.y+oy;if(x<-80||x>W+80||y<-80||y>H+80)continue;ctx.font="26px serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText({tree:"🌳",ore:"⛏️",chest:"📦",city:"🏰",cave:"🕳️",mob:"👹"}[e.type],x,y);if(e.type==="mob"){ctx.fillStyle="#16191c";ctx.fillRect(x-18,y-25,36,4);ctx.fillStyle="#d74d4d";ctx.fillRect(x-18,y-25,36*Math.max(0,e.hp/35),4)}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.c;ctx.fillRect(p.x+ox-3,p.y+oy-3,6,6)}ctx.globalAlpha=1;ctx.font="30px serif";ctx.fillText("🧙",W/2,H/2);document.querySelector("#hp").style.width=player.hp+"%";document.querySelector("#mana").style.width=player.mana+"%";document.querySelector("#aura").style.width=player.aura+"%";document.querySelector("#gold").textContent="◈ "+player.gold;document.querySelector("#stats").textContent="Lv."+player.level+" • Madeira "+player.wood+" • Minério "+player.ore}
let last=performance.now();function loop(now=performance.now()){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}if(localStorage.getItem("hg_provider"))login.classList.add("hidden");loop();